
export enum E_CALL_STATE_ACTIONS {
  API_GET_USER = "API_GET_USER",
  API_UPDATE_USER_PROFILE = "API_UPDATE_USER_PROFILE",
  API_UPDATE_USER_CREDENTIALS = "API_UPDATE_USER_CREDENTIALS",
  API_USER_LOGOUT = "API_USER_LOGOUT"
}

