version: "3.7"
services:
  # reverse proxy
  apim-devel-www:
    container_name: apim-devel-www
    image: nginx:1.21.4-alpine
    restart: unless-stopped
    ports:
      - 3002:80
    volumes:
      - ./docker-volumes/apim-www/nginx.conf:/etc/nginx/nginx.conf
      - ./docker-volumes/apim-www-logs:/etc/nginx/logs
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "2"

##
# The End.
