version: "3.7"
services:
  # reverse proxy
  qs-async-apim-www:
    container_name: qs-async-apim-www
    image: nginx:1.21.4-alpine
    restart: unless-stopped
    ports:
      - 5000:80
    links:
      - qs-async-apim-admin-portal
      - qs-async-apim-connector
      - qs-async-apim-server
    volumes:
      - ./docker-volumes/apim-www/nginx.conf:/etc/nginx/nginx.conf
      - ./docker-volumes/apim-www-logs:/etc/nginx/logs
  qs-async-apim-admin-portal:
    container_name: qs-async-apim-admin-portal
    image : "solaceiotteam/async-apim-admin-portal:latest"
    # image : "solaceiotteam/async-apim-admin-portal:0.0.21"
    ports:
      - 5080:80
    restart: unless-stopped
  qs-async-apim-server-mongodb:
    container_name: qs-async-apim-server-mongodb
    image : mongo:5.0.2
    volumes:
      - ./docker-volumes/apim-server-mongodb-data:/data/db
    restart: unless-stopped
  qs-async-apim-server:
    container_name: qs-async-apim-server
    links:
      - qs-async-apim-connector
      - qs-async-apim-server-mongodb
    image: "solaceiotteam/async-apim-server:latest"
    ports:
      - 5002:3000
    volumes:
      - ./docker-volumes/apim-server:/data
    restart: unless-stopped
    environment:
      # apim server
      - APIM_SERVER_PORT=3000
      - APIM_SERVER_API_BASE=/apim-server/v1
      - APIM_SERVER_MONGO_CONNECTION_STRING=mongodb://qs-async-apim-server-mongodb:27017/?retryWrites=true&w=majority
      - APIM_SERVER_MONGO_DB=solace-apim-server
      - APIM_SERVER_OPENAPI_ENABLE_RESPONSE_VALIDATION=false
      - APIM_SERVER_LOGGER_APP_ID=apim-server
      - APIM_SERVER_LOGGER_LOG_LEVEL=trace
      - APIM_SERVER_REQUEST_SIZE_LIMIT=100kb
      - APIM_SERVER_SECRET=mySecret
      - APIM_SERVER_OPENAPI_SPEC_PATH=/apim-server/v1/spec
      - APIM_SERVER_ROOT_USER=root.admin@aps.com
      - APIM_SERVER_ROOT_USER_PWD=admin123!
      - APIM_SERVER_DATA_PATH=/data

  # apim connector
  qs-async-apim-connector-mongodb:
    container_name: qs-async-apim-connector-mongodb
    image : mongo:5.0.2
    volumes:
      - ./docker-volumes/apim-connector-mongodb-data:/data/db
    restart: unless-stopped
  qs-async-apim-connector:
    container_name: qs-async-apim-connector
    links:
      - qs-async-apim-connector-mongodb
    image: "solaceiotteam/apim-connector-server:latest"
    # image: "solaceiotteam/apim-connector-server:0.3.2"
    ports:
      - 5001:3000
    volumes:
      - ./docker-volumes/apim-connector:/data
    restart: unless-stopped
    environment:
      - DB_URL="mongodb://qs-async-apim-connector-mongodb:27017/platform?retryWrites=true&w=majority"
      - LOG_LEVEL=trace
      - APP_ID=qs-async-apim-connector
      - FILE_USER_REGISTRY=/data/organization_users.json
      - PLATFORM_PORT=3000
      - AUTH_EXTRACTION_USER_PRINCIPAL="$$.preferred_username"
      - AUTH_EXTRACTION_ORGS="$$.organization"
      - AUTH_EXTRACTION_ROLES="$$.groups"
      - AUTH_VERIFICATION_KEY=/data/dummy.pem
      - AUTH_VERIFICATION_ISSUER="https://dev-1.okta.com/oauth2/default"
      - AUTH_VERIFICATION_AUD="0oancf26sFegoXz8l5d6"
      - AUTH_DISCOVERY_OIDC_URL=https://dev-1.okta.com/x/oauth2/default/.well-known/openid-configuration
      # - APIS_PROXY_MODE=false

##
# The End.
