export enum EAction {
  EDIT = 'EDIT',
  NEW = 'NEW'
}
export enum E_CALL_STATE_ACTIONS {
  API_GET_EMPTY_API_PRODUCT = "API_GET_EMPTY_API_PRODUCT",
  API_GET_API_PRODUCT_LIST = "API_GET_API_PRODUCT_LIST",
  API_GET_API_PRODUCT = "API_GET_API_PRODUCT",
  API_UPDATE_API_PRODUCT = "API_UPDATE_API_PRODUCT",
  API_DELETE_API_PRODUCT = "API_DELETE_API_PRODUCT",
  API_CREATE_API_PRODUCT = "API_CREATE_API_PRODUCT",
  API_GET_API_SPEC = "API_GET_API_SPEC",
  API_GET_ENVIRONMENT_LIST = "API_GET_ENVIRONMENT_LIST",  
  API_GET_API_INFO_LIST = "API_GET_API_INFO_LIST",
  API_CHECK_API_PRODUCT_ID_EXISTS = "API_CHECK_API_PRODUCT_ID_EXISTS",
  // API_GET_API = 'API_GET_API',
  // SELECT_APIS = "SELECT_APIS",
  // SELECT_ENVIRONMENTS = "SELECT_ENVIRONMENTS",
}

export enum E_COMPONENT_STATE {
  UNDEFINED = "UNDEFINED",
  MANAGED_OBJECT_LIST_VIEW = "MANAGED_OBJECT_LIST_VIEW",
  MANAGED_OBJECT_VIEW = "MANAGED_OBJECT_VIEW",
  MANAGED_OBJECT_EDIT = "MANAGED_OBJECT_EDIT",
  MANAGED_OBJECT_DELETE = "MANAGED_OBJECT_DELETE",
  MANAGED_OBJECT_NEW = "MANAGED_OBJECT_NEW"
}

export enum E_COMPONENT_STATE_EDIT {
  UNDEFINED = "UNDEFINED",
  PROFILE = "PROFILE",
  ROLES_AND_GROUPS = "ROLES_AND_GROUPS",
  AUTHENTICATION = "AUTHENTICATION",
  REVIEW = "REVIEW"
}

export enum E_COMPONENT_STATE_NEW {
  UNDEFINED = "UNDEFINED",
  GENERAL = "GENERAL",
  APIS = "APIS",
  POLICIES = "POLICIES",
  ENVIRONMENTS = "ENVIRONMENTS",
  ATTRIBUTES = "ATTRIBUTES",
  REVIEW = "REVIEW"
}
