
export const ButtonLabel_Next = "Next";
export const ButtonLabel_Back = "Back";
export const ButtonLabel_Cancel = "Cancel";
export const ButtonLabel_Create = "Create";
export const ButtonLabel_SaveLifecycle = "Update";
export const ButtonLabel_CreateNewVersion = "Create New Version";

export enum EAction {
  EDIT = 'EDIT',
  EDIT_RECOVERABLE = 'EDIT_RECOVERABLE',
  NEW = 'NEW'
}
export enum E_CALL_STATE_ACTIONS {
  API_GET_EMPTY_API_PRODUCT = "API_GET_EMPTY_API_PRODUCT",
  API_GET_API_PRODUCT_LIST = "API_GET_API_PRODUCT_LIST",
  API_GET_API_PRODUCT = "API_GET_API_PRODUCT",
  API_DELETE_API_PRODUCT = "API_DELETE_API_PRODUCT",
  API_CREATE_VERSION_API_PRODUCT = "API_CREATE_VERSION_API_PRODUCT",
  API_GET_API_SPEC = "API_GET_API_SPEC",
  API_GET_ENVIRONMENT_LIST = "API_GET_ENVIRONMENT_LIST",  
  API_GET_API_INFO_LIST = "API_GET_API_INFO_LIST",
  API_CHECK_API_PRODUCT_ID_EXISTS = "API_CHECK_API_PRODUCT_ID_EXISTS",
}

export enum E_COMPONENT_STATE {
  UNDEFINED = "UNDEFINED",
  MANAGED_OBJECT_LIST_VIEW = "MANAGED_OBJECT_LIST_VIEW",
  MANAGED_OBJECT_VIEW = "MANAGED_OBJECT_VIEW",
  MANAGED_OBJECT_EDIT = "MANAGED_OBJECT_EDIT",
  MANAGED_OBJECT_DELETE = "MANAGED_OBJECT_DELETE",
  MANAGED_OBJECT_NEW = "MANAGED_OBJECT_NEW",
  MANAGED_OBJECT_LIST_RECOVER = "MANAGED_OBJECT_LIST_RECOVER"
}

export enum E_COMPONENT_STATE_EDIT_NEW {
  UNDEFINED = "UNDEFINED",
  GENERAL = "GENERAL",
  APIS = "APIS",
  POLICIES = "POLICIES",
  ENVIRONMENTS = "ENVIRONMENTS",
  ATTRIBUTES = "ATTRIBUTES",
  ACCESS_AND_STATE = "ACCESS_AND_STATE",
  REVIEW = "REVIEW"
}

export enum E_COMPONENT_STATE_RECOVER {
  UNDEFINED = "UNDEFINED",
  MANAGED_OBJECT_LIST_VIEW = "MANAGED_OBJECT_LIST_VIEW",
  MANAGED_OBJECT_VIEW = "MANAGED_OBJECT_VIEW",
  MANAGED_OBJECT_EDIT = "MANAGED_OBJECT_EDIT",
  MANAGED_OBJECT_DELETE = "MANAGED_OBJECT_DELETE",
}
