export enum E_CALL_STATE_ACTIONS {
  API_GET_EXTERNAL_SYSTEM_LIST = "API_GET_EXTERNAL_SYSTEM_LIST",
  API_GET_EXTERNAL_SYSTEM = "API_GET_EXTERNAL_SYSTEM",
  API_CREATE_EXTERNAL_SYSTEM = "API_CREATE_EXTERNAL_SYSTEM",
  API_UPDATE_EXTERNAL_SYSTEM = "API_UPDATE_EXTERNAL_SYSTEM",
  API_DELETE_EXTERNAL_SYSTEM = "API_DELETE_EXTERNAL_SYSTEM",
}


