export enum E_CALL_STATE_ACTIONS {
  API_GET_BUSINESS_GROUP_LIST = "API_GET_BUSINESS_GROUP_LIST",
  API_GET_BUSINESS_GROUP = "API_GET_BUSINESS_GROUP",
  API_CREATE_BUSINESS_GROUP = "API_CREATE_BUSINESS_GROUP",
  API_UPDATE_BUSINESS_GROUP = "API_UPDATE_BUSINESS_GROUP",
  API_DELETE_BUSINESS_GROUP = "API_DELETE_BUSINESS_GROUP",
  API_GET_EXTERNAL_SYSTEM_LIST_CAPABLE_OF_INTERACTIVE_IMPORT_OF_BUSINESS_GRAOUPS = "API_GET_EXTERNAL_SYSTEM_LIST_CAPABLE_OF_INTERACTIVE_IMPORT_OF_BUSINESS_GRAOUPS"
}


