
export type TManagedObjectId = string;

export enum E_CALL_STATE_ACTIONS {
  API_GET_APP_LIST = "API_GET_APP_LIST",
  API_GET_APP = "API_GET_APP",
  API_UPDATE_APP = "API_UPDATE_APP",
  API_APPROVE_APP = "API_APPROVE_APP",
  API_REVOKE_APP = "API_REVOKE_APP",
  API_DELETE_APP = "API_DELETE_APP",
  API_GET_USER = "API_GET_USER"
}

export enum E_COMPONENT_STATE {
  UNDEFINED = "UNDEFINED",
  MANAGED_OBJECT_LIST_VIEW = "MANAGED_OBJECT_LIST_VIEW",
  MANAGED_OBJECT_VIEW = "MANAGED_OBJECT_VIEW",
  MANAGED_OBJECT_EDIT_ATTRIBUTES = "MANAGED_OBJECT_EDIT_ATTRIBUTES",
  MANAGED_OBJECT_APPROVE = "MANAGED_OBJECT_APPROVE",
  MANAGED_OBJECT_REVOKE = "MANAGED_OBJECT_REVOKE",
  MANAGED_OBJECT_DELETE = "MANAGED_OBJECT_DELETE",
  MANAGED_OBJECT_MONITOR = "MANAGED_OBJECT_MONITOR"
}

