
export type TManagedObjectId = string;

export enum E_CALL_STATE_ACTIONS {
  API_GET_APP_LIST = "API_GET_APP_LIST",
  API_GET_APP = "API_GET_APP",
  API_UPDATE_APP = "API_UPDATE_APP",
  API_APPROVE_APP = "API_APPROVE_APP",
  API_REVOKE_APP = "API_REVOKE_APP",
  API_DELETE_APP = "API_DELETE_APP",
  API_GET_USER = "API_GET_USER"
}


