export enum E_CALL_STATE_ACTIONS {
  API_GET_API_PRODUCT_LIST = "API_GET_API_PRODUCT_LIST",
  API_DELETE_API_PRODUCT = "API_DELETE_API_PRODUCT",
  API_CREATE_VERSION_API_PRODUCT = "API_CREATE_VERSION_API_PRODUCT",
}

export enum E_COMPONENT_STATE {
  UNDEFINED = "UNDEFINED",
  MANAGED_OBJECT_LIST_VIEW = "MANAGED_OBJECT_LIST_VIEW",
  MANAGED_OBJECT_VIEW = "MANAGED_OBJECT_VIEW",
  MANAGED_OBJECT_EDIT = "MANAGED_OBJECT_EDIT",
  MANAGED_OBJECT_DELETE = "MANAGED_OBJECT_DELETE",
}

