export enum E_CALL_STATE_ACTIONS {
  API_GET_USER_APP_LIST = "API_GET_USER_APP_LIST",
  API_DELETE_USER_APP = "API_DELETE_USER_APP",
  API_CREATE_USER_APP = "API_CREATE_USER_APP",
  API_GET_USER_APP = "API_GET_USER_APP",
  API_GET_EMPTY_USER_APP = "API_GET_EMPTY_USER_APP",
  API_UPDATE_USER_APP = "API_UPDATE_USER_APP",
  API_GET_API_PRODUCT_LIST = "API_GET_API_PRODUCT_LIST",
  SELECT_API_PRODUCTS = "SELECT_API_PRODUCTS",
  API_CHECK_DEVELOPER_EXISTS = "API_CHECK_DEVELOPER_EXISTS",
}

export enum E_MANAGE_USER_APP_COMPONENT_STATE {
  UNDEFINED = "UNDEFINED",
  INTERNAL_ERROR = "INTERNAL_ERROR",
  MANAGED_OBJECT_LIST_VIEW = "MANAGED_OBJECT_LIST_VIEW",
  MANAGED_OBJECT_VIEW = "MANAGED_OBJECT_VIEW",
  MANAGED_OBJECT_EDIT = "MANAGED_OBJECT_EDIT",
  MANAGED_OBJECT_MANAGE_WEBHOOKS = "MANAGED_OBJECT_MANAGE_WEBHOOKS",
  MANAGED_OBJECT_DELETE = "MANAGED_OBJECT_DELETE",
  MANAGED_OBJECT_NEW = "MANAGED_OBJECT_NEW",
  MANAGED_OBJECT_MONITOR = "MANAGED_OBJECT_MONITOR"
}

// export enum E_MANAGE_WEBHOOK_COMPONENT_STATE {
//   UNDEFINED = "UNDEFINED",
//   MANAGED_OBJECT_LIST_VIEW = "MANAGED_OBJECT_LIST_VIEW",
//   MANAGED_OBJECT_VIEW = "MANAGED_OBJECT_VIEW",
//   MANAGED_OBJECT_NEW = "MANAGED_OBJECT_NEW",
//   MANAGED_OBJECT_EDIT = "MANAGED_OBJECT_EDIT",
//   MANAGED_OBJECT_DELETE = "MANAGED_OBJECT_DELETE"
// }

export enum E_MONITOR_COMPONENT_STATE {
  UNDEFINED = "UNDEFINED",
  MANAGED_OBJECT_VIEW = "MANAGED_OBJECT_VIEW",
}

export enum EAction {
  EDIT = 'EDIT',
  NEW = 'NEW'
}
