import { TAPEntityId } from "../../../utils/APEntityIdsService";

export enum E_ManageOrganizations_Scope {
  ALL_ORGS = "ALL_ORGS",
  ORG_SETTINGS = "ORG_SETTINGS",
  ORG_STATUS = "ORG_STATUS"
}
export type TManageOrganizationSettingsScope = {
  type: E_ManageOrganizations_Scope.ORG_SETTINGS;
  organizationEntityId: TAPEntityId;
};
export type TMonitorOrganizationStatusScope = {
  type: E_ManageOrganizations_Scope.ORG_STATUS;
  organizationEntityId: TAPEntityId;
};
export type TManageAllOrganizationsScope = {
  type: E_ManageOrganizations_Scope.ALL_ORGS;
}
export type TManageOrganizationsScope = 
  TManageOrganizationSettingsScope
  | TManageAllOrganizationsScope
  | TMonitorOrganizationStatusScope;


export enum E_COMPONENT_STATE {
  UNDEFINED = "UNDEFINED",
  MANAGED_OBJECT_LIST_VIEW = "MANAGED_OBJECT_LIST_VIEW",
  MANAGED_OBJECT_VIEW = "MANAGED_OBJECT_VIEW",
  MANAGED_OBJECT_EDIT = "MANAGED_OBJECT_EDIT",
  MANAGED_OBJECT_DELETE = "MANAGED_OBJECT_DELETE",
  MANAGED_OBJECT_NEW = "MANAGED_OBJECT_NEW",
  MONITOR_OBJECT = "MONITOR_OBJECT",
  MANAGE_ORGANIZATION_USERS = "MANAGE_ORGANIZATION_USERS"
}

export enum E_CALL_STATE_ACTIONS {
  API_DELETE_ORGANIZATION = "API_DELETE_ORGANIZATION",
  API_GET_ORGANIZATION_LIST = "API_GET_ORGANIZATION_LIST",
  API_CREATE_ORGANIZATION = "API_CREATE_ORGANIZATION",
  API_GET_ORGANIZATION = "API_GET_ORGANIZATION",
  API_UPDATE_ORGANIZATION = "API_UPDATE_ORGANIZATION",
  API_GET_ORGANIZATION_ASSETS = "API_GET_ORGANIZATION_ASSETS",
  API_LOGOUT_ORGANIZATION_ALL = "API_LOGOUT_ORGANIZATION_ALL",
}

export enum E_COMPONENT_STATE_USERS {
  UNDEFINED = "UNDEFINED",
  MANAGED_OBJECT_LIST_VIEW = "MANAGED_OBJECT_LIST_VIEW",
  MANAGED_OBJECT_EDIT_ROLES = "MANAGED_OBJECT_EDIT_ROLES",
  MANAGED_OBJECT_ADD = "MANAGED_OBJECT_ADD",
}

export enum E_COMPONENT_STATE_ADD_USER {
  UNDEFINED = "UNDEFINED",
  SYSTEM_USER_LIST_VIEW = "SYSTEM_USER_LIST_VIEW",
  EDIT_USER_ROLES = "EDIT_USER_ROLES",
}

export enum E_CALL_STATE_ACTIONS_USERS {
  API_GET_USER_LIST = "API_GET_USER_LIST",
  API_GET_USER = "API_GET_USER",
  API_UPDATE_USER_ROLES = "API_UPDATE_USER_ROLES",
  API_ADD_USER = "API_ADD_USER",
  API_CREATE_ORGANIZATION_USER_FROM_SYSTEM_USER = "API_CREATE_ORGANIZATION_USER_FROM_SYSTEM_USER",
  API_ADD_USER_TO_ORG = "API_ADD_USER_TO_ORG",
  API_USER_LOGOUT = "API_USER_LOGOUT"
}

