
export const DoLogoutAllUsers: boolean = false;

export enum EAction {
  EDIT = 'EDIT',
  NEW = 'NEW'
}

export enum EManageEpSettingsScope {
  VIEW = "VIEW",
  EDIT = "EDIT"
}
export enum E_COMPONENT_STATE {
  UNDEFINED = "UNDEFINED",
  MANAGED_OBJECT_LIST_VIEW = "MANAGED_OBJECT_LIST_VIEW",
  MANAGED_OBJECT_VIEW = "MANAGED_OBJECT_VIEW",
  MANAGED_OBJECT_EDIT = "MANAGED_OBJECT_EDIT",
  MANAGED_OBJECT_DELETE = "MANAGED_OBJECT_DELETE",
  MANAGED_OBJECT_NEW = "MANAGED_OBJECT_NEW",
  MONITOR_OBJECT = "MONITOR_OBJECT",
  MANAGED_OBJECT_RUN = "MANAGED_OBJECT_RUN",
}

export enum E_CALL_STATE_ACTIONS {
  API_CHECK_ID_EXISTS = "API_CHECK_ID_EXISTS",
  API_DELETE = "API_DELETE",
  API_GET_LIST = "API_GET_LIST",
  API_CREATE = "API_CREATE",
  API_GET = "API_GET",
  API_UPDATE = "API_UPDATE",
  API_GET_BUSINESS_GROUP_TREE_LIST = "API_GET_BUSINESS_GROUP_TREE_LIST",
  API_GET_APPLICATION_DOMAIN_LIST = "API_GET_APPLICATION_DOMAIN_LIST",
  API_GET_PUBLISH_DESTINATIONS = "API_GET_PUBLISH_DESTINATIONS",
  API_RUN_IMPORT_JOB = "API_RUN_IMPORT_JOB",
}

