
export enum E_CALL_STATE_ACTIONS {
  API_LOGIN = "API_LOGIN",
  API_SETUP_LOGIN_CONTEXTS = "API_SETUP_LOGIN_CONTEXTS",
  API_GET_LOGIN = "API_GET_LOGIN",
}

export enum E_COMPONENT_STATE {
  UNDEFINED = "UNDEFINED",
  LOGIN_SCREEN = "LOGIN_SCREEN",
  SELECT_ORGANIZATION = "SELECT_ORGANIZATION",
}

