
export enum E_CALL_STATE_ACTIONS {
  // xxxx = "xxxx",
  API_LOGIN = "API_LOGIN",
  // API_GET_USER_LIST = "API_GET_USER_LIST",
  // API_GET_USER = "API_GET_USER",
  // API_GET_EMPTY_USER = "API_GET_EMPTY_USER",
  // API_CREATE_USER = "API_CREATE_USER", 
  // API_UPDATE_USER = "API_UPDATE_USER",
  // API_DELETE_USER = "API_DELETE_USER",
  // API_CHECK_USER_EXISTS = "API_CHECK_USER_EXISTS",
}

export enum E_COMPONENT_STATE {
  UNDEFINED = "UNDEFINED",
  LOGIN_SCREEN = "LOGIN_SCREEN",
  SELECT_ORGANIZATION = "SELECT_ORGANIZATION",
}

