
export enum E_COMPONENT_STATE {
  UNDEFINED = "UNDEFINED",
  MANAGED_OBJECT_LIST_VIEW = "MANAGED_OBJECT_LIST_VIEW",
  MANAGED_OBJECT_VIEW = "MANAGED_OBJECT_VIEW",
}

export enum E_CALL_STATE_ACTIONS {
  API_GET_LIST = "API_GET_LIST",
  API_GET = "API_GET",
}

