
export enum E_CALL_STATE_ACTIONS {
  API_GET_USER_APP = "API_GET_USER_APP",
  API_GET_APP_WEBHOOK_LIST = "API_GET_APP_WEBHOOK_LIST",
}

export enum E_COMPONENT_STATE {
  UNDEFINED = "UNDEFINED",
  LIST_VIEW = "LIST_VIEW",
  VIEW = "VIEW",
  NEW = "NEW",
  EDIT = "EDIT",
  DELETE = "DELETE"
}

