version: "3.7"
services:
  apim-devel-mongodb:
    container_name: apim-devel-mongodb
    image : mongo:5.0.2
    ports:
      - 27019:27017
    volumes:
      - ./docker-volumes/apim-devel-mongodb-data:/data/db
    restart: unless-stopped
  apim-devel-connector:
    container_name: ${APIM_DEVEL_CONNECTOR_CONTAINER_NAME}
    links:
      - apim-devel-mongodb
    image: "solaceiotteam/apim-connector-server:latest"
    ports:
      - 9095:3000
    volumes:
      - ./docker-volumes/apim-connector:/data
    restart: unless-stopped
    environment:
      - DB_URL="mongodb://apim-devel-mongodb:27017/platform?retryWrites=true&w=majority"
      - LOG_LEVEL=trace
      - APP_ID="apim-devel-connector"
      - FILE_USER_REGISTRY=/data/organization_users.json
      - PLATFORM_PORT=3000
      - AUTH_EXTRACTION_USER_PRINCIPAL=$$.userId
      - AUTH_EXTRACTION_ORGS=$$.organization
      - AUTH_EXTRACTION_ROLES=$$.roles
      - AUTH_VERIFICATION_KEY=/data/secret.txt
      - AUTH_VERIFICATION_ISSUER=apim-server
      - AUTH_VERIFICATION_AUD=platform-api-server
      - AUTH_DISCOVERY_OIDC_URL=https://dev-1.okta.com/x/oauth2/default/.well-known/openid-configuration
      # - APIS_PROXY_MODE=false

##
# The End.
