###########################################################################
# Dockerfile
###########################################################################

FROM node:14.17.5

COPY dist /usr/local/apim-portal/dist

CMD /usr/local/apim-portal/start.sh

# The end.
